\input texinfo   @c -*-texinfo-*-
@comment %**start of header
@setfilename markdown-mode.info
@settitle Emacs Markdown Mode
@comment created under texinfo 6.1
@set EDITION WIP Edition
@set VERSION 2.1
@set RELEASED January 9, 2016
@set SWCYEARS 2007-2016
@syncodeindex fn cp
@syncodeindex vr cp
@syncodeindex ky cp
@comment %**end of header

@copying
Copyright @copyright{} 2016 Daniel Birket.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
Texts.  A copy of the license is included in the section entitled
``GNU Free Documentation License''.
@end quotation

This is the Emacs Markdown Mode manual (unauthorized),
@value{EDITION}, by Daniel Birket.

It describes how to use the Emacs Lisp package @code{markdown-mode},
version @value{VERSION}, released @value{RELEASED}, by and Copyright
@copyright{} @value{SWCYEARS} Jason R. Blevins, et al.

The @emph{authorized} manual for @code{markdown-mode} is online at
@uref{http://jblevins.org/projects/markdown-mode/}.

This manual is based upon the extensive documentation in the
@code{markdown-mode.el} source code, which includes this notice:

@lisp
;; This file is not part of GNU Emacs.

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
@end lisp
@xref{GNU General Public License 2.0}.
@end copying

@dircategory Emacs editing modes
@direntry
* markdown-mode: (markdown-mode).        Emacs mode for markdown-formatted text.
@end direntry

@titlepage
@title Emacs Markdown Mode
@subtitle (Unauthorized) @value{EDITION}
@author Daniel Birket,
@author Jason R. Blevins, et al.
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnotdocbook
@ifnottex
@node Top
@top Emacs Markdown Mode
This manual describes how to use @code{markdown-mode}, an Emacs
package for editing markdown-formatted text.

@insertcopying
@end ifnottex
@end ifnotdocbook

@menu
* Introduction::                        About @command{markdown} & @code{markdown-mode}
* Installation::                        How to Download & Install.
* GNU General Public License 2.0::      1991 GPL used by markdown-mode.el
* GNU Free Documentation License::      used by this manual
* Index::
@end menu

@node Introduction
@chapter Introduction
@cindex markdown

TBD Introduction Chapter Text

The program @command{markdown} and markdown-format is described at
@uref{http://daringfireball.net/projects/markdown/}.


@node Installation
@chapter Installation
@cindex Installing markdown-mode
@cindex Downloading markdown-mode
@cindex How to Install markdown-mode

TBD Installation Chapter Text

@node GNU General Public License 2.0
@unnumbered GNU General Public License 2.0
@include gpl-2.0.texi


@node GNU Free Documentation License
@unnumbered GNU Free Documentation License
@include fdl.texi


@node Index
@unnumbered Index
@printindex cp

@bye
