\input texinfo   @c -*-texinfo-*-
@comment %**start of header
@setfilename markdown-mode.info
@settitle Emacs Markdown Mode
@comment created under texinfo 6.1
@set EDITION Working Draft
@set VERSION 2.1
@set RELEASED January 9, 2016
@set SWCYEARS 2007-2016
@syncodeindex fn cp
@syncodeindex vr cp
@syncodeindex ky cp
@comment %**end of header

@comment =============================================================
@copying
@cindex Copyright (manual)
Copyright @copyright{} 2016 Daniel Birket.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
Texts.  A copy of the license is included in the section entitled
``GNU Free Documentation License''.
@end quotation

This is the Emacs Markdown Mode manual (unauthorized),
@value{EDITION}, by Daniel Birket.  It describes how to install and
use the Emacs Lisp package @code{markdown-mode}, version
@value{VERSION}, released @value{RELEASED}, written by and Copyright
@copyright{} @value{SWCYEARS} Jason R. Blevins, et al.  The
@code{markdown-mode} package and its @emph{authorized} manual are
online at @uref{http://jblevins.org/projects/markdown-mode/}.

This manual is based upon the extensive documentation in the
@code{markdown-mode.el} source code, which includes these lines:

@cindex Copyright (software)
@lisp
;; Copyright (C) 2007-2016 Jason R. Blevins <jrblevin@@sdf.org>
...
;; This file is not part of GNU Emacs.

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
@end lisp
@end copying

@comment =============================================================
@dircategory Emacs editing modes
@direntry
* markdown-mode: (markdown-mode).        Emacs mode for markdown-formatted text.
@end direntry

@comment =============================================================
@titlepage
@title Emacs Markdown Mode
@subtitle (Unauthorized)
@subtitle @value{EDITION}
@author Daniel Birket,
@author Jason R. Blevins, et al.
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@comment =============================================================
@ifnotdocbook
@ifnottex
@node Top
@top Emacs Markdown Mode
This manual describes how to install and use @code{markdown-mode}, an Emacs
package for working with markdown-formatted text.

@ifinfo
In @command{info}, hit @kbd{3} to jump to usage chapter.

@end ifinfo
@insertcopying
@end ifnottex
@end ifnotdocbook

@menu
* Introduction::                About @command{markdown} & @code{markdown-mode}.
* Installing::                  How to Download & Install @code{markdown-mode}.
* Using Markdown Mode::         How to Use @code{markdown-mode}.
* Using GFM Mode::              How to Use @code{gfm-mode}.
* Customizing::                 How to Customize @code{markdown-mode} (Variables).
* Using Extensions::            How to Use Supported Extensions.

Appendices
* Development::                 For those who contribute, then or now.
* GNU General Public License 2.0::  License of @code{markdown-mode.el} (1991).
* GNU General Public License 3.0::  Optional updated license (2007).
* GNU Free Documentation License::  License of this manual (2008).
* Index::
@end menu

@comment =============================================================
@node Introduction
@chapter Introduction
@cindex markdown

This manual describes how to install and use @code{markdown-mode}, an Emacs
package for working with markdown-formatted text.

The package implements two Emacs ``major modes'':
@itemize @bullet
@item
@code{markdown-mode}, for editing standard markdown text.
@xref{Using Markdown Mode}

@item
@code{gfm-mode}, for editing GitHub-flavored markdown text.
@xref{Using GFM Mode}
@end itemize

@command{markdown} is an popular and easy way to write styled text with
simple text files.  It is described at
@uref{http://daringfireball.net/projects/markdown/}.

GitHub Flavored Markdown is the dialect of markdown used by GitHub. It
is described at
@uref{http://github.github.com/github-flavored-markdown/}.

@command{emacs} is the world's most powerful text editor.  It is highly
extensible and has a large ecosystem of extensions like this one.  GNU
emacs is described at @uref{https://www.gnu.org/software/emacs/}.

@comment =============================================================
@node Installing
@chapter Installing
@cindex Downloading
@cindex How to Download
@cindex How to Install

ToDo Chapter Text

@menu
* Recommended Installation::    How to Install with @code{package.el}.
* Managed Loading::             How to Manage with @code{use-package.el}.
* OS Package Managers::         How to Install with OS Package Managers.
* Manual Installation::         How to Install the hard way.
@end menu

@comment -------------------------------------------------------------
@node Recommended Installation
@section Recommended Installation
@cindex How to Install using @code{package.el}
@cindex MELPA Stable
@findex package.el
@findex package-install

ToDo Section Text

This package @code{markdown-mode} depends on the package @code{cl-lib},
which has been bundled with GNU Emacs since version 24.3. If you use
GNU Emacs version 24.1 or 24.2, you should install @code{cl-lib} using
@code{package.el}.

ToDo add instructions to install cl-lib

@comment -------------------------------------------------------------
@node Managed Loading
@section Managed Loading
@cindex How to Manage with @code{use-package}
@findex use-package.el

ToDo Section Text

@comment -------------------------------------------------------------
@node OS Package Managers
@section OS Package Managers
@cindex How to Install as a Linux Package
@cindex How to Install as a Debian Package
@cindex How to Install as a Ubuntu Package
@cindex How to Install as a Fedora Package
@cindex How to Install as a FreeBSD Package
@cindex How to Install as a MacPorts Package

ToDo Section Text

@comment -------------------------------------------------------------
@node Manual Installation
@section Manual Installation
@cindex How to Install Manually
@cindex How to Download Manully

ToDo Section Text

@comment =============================================================
@node Using Markdown Mode
@chapter Using Markdown Mode
@cindex Usage
@cindex How to Use markdown-mode
@findex markdown-mode

ToDo Chapter Text

@comment =============================================================
@node Using GFM Mode
@chapter Using GFM Mode
@cindex GitHub Flavored Markdown
@cindex How to Use gfm-mode
@findex gfm-mode

ToDo Chapter Text

@comment =============================================================
@node Customizing
@chapter Customizing
@cindex How to Customize
@cindex Variables

ToDo Chapter Text

@comment =============================================================
@node Using Extensions
@chapter Using Extensions
@cindex Extensions
@cindex How to Use Extensions

ToDo Chapter Text

@menu
* SmartyPants::                 Smart Quotation Marks.
* LaTeX Math::                  Highlight LaTeX Math Syntax
* Wiki Links::                  Highlight Wiki Links Syntax
@end menu

@comment -------------------------------------------------------------
@node SmartyPants
@section SmartyPants
@cindex How to Use SmartyPants
@cindex Smart Quote Marks

ToDo Section Text

@comment -------------------------------------------------------------
@node LaTeX Math
@section LaTeX Math
@cindex Highlighting LaTeX Math Syntax
@cindex LaTeX Math Syntax Highlighting
@cindex How to Highlight LaTeX Math

ToDo Section Text

@comment -------------------------------------------------------------
@node Wiki Links
@section Wiki Links
@cindex Highlighting Wiki Links Syntax
@cindex Wiki Links Syntax Highlighting
@cindex How to Highlight Wiki Links

ToDo Section Text

@comment =============================================================
@node Development
@appendix Development

ToDo Chapter Text

@menu
* Acknowledgements::            Many Thanks to Contributors.
* History of Releases::         History of Software Releases.
* Development Version::         How to Get the Development Software.
* Bugs and Errors::             How to Report Bugs and Errors.
@end menu

@comment -------------------------------------------------------------
@node Acknowledgements
@section Acknowledgements
@cindex Contributors
@cindex Credits

ToDo Section Text

@comment -------------------------------------------------------------
@node History of Releases
@section History of Releases
@cindex History
@cindex Releases

ToDo Section Text

@comment -------------------------------------------------------------
@node Development Version
@section Development Version
@cindex How to Get Development Version
@cindex How to Install Development Version

ToDo Section Text

@comment -------------------------------------------------------------
@node Bugs and Errors
@section Bugs and Errors
@cindex How to Report Bugs
@cindex How to Report Errors
@cindex Feedback
@cindex Contact Information

ToDo Section Text

@comment =============================================================
@node GNU General Public License 2.0
@cindex License (software)
@unnumbered GNU General Public License 2.0

@include gpl-2.0.texi

@comment =============================================================
@node GNU General Public License 3.0
@cindex License (updated)
@unnumbered GNU General Public License 3.0

@include gpl.texi

@comment =============================================================
@node GNU Free Documentation License
@cindex License (manual)
@unnumbered GNU Free Documentation License

@include fdl.texi

@comment =============================================================
@node Index
@unnumbered Index

@printindex cp

@bye
